export const arrayNewCoworkingForm = [
  {
    name: 'name',
    label: 'Nombre',
    type: 'text',
    placeholder: 'Nombre',
    required: true,
  },
  {
    name: 'phone',
    label: 'Teléfono',
    type: 'text',
    placeholder: 'Teléfono',
    required: true,
  },
  {
    name: 'email',
    label: 'Correo electrónico',
    type: 'email',
    placeholder: 'Correo electrónico',
    required: true,
  },
  {
    name: 'open',
    label: 'Horario de apertura',
    type: 'time',
    placeholder: 'Horario de apertura',
    required: false,
  },
  {
    name: 'close',
    label: 'Horario de cierre',
    type: 'time',
    placeholder: 'Horario de cierre',
    required: false,
  },
  {
    name: 'address',
    label: 'Dirección',
    type: 'text',
    placeholder: 'Dirección',
    required: false,
  },
  {
    name: 'country',
    label: 'País',
    type: 'text',
    placeholder: 'País',
    required: false,
  },
  {
    name: 'state',
    label: 'Provincia/Estado',
    type: 'text',
    placeholder: 'Provincia/Estado',
    required: false,
  },
  {
    name: 'city',
    label: 'Ciudad',
    type: 'text',
    placeholder: 'Ciudad',
    required: false,
  },
  {
    name: 'capacity',
    label: 'Cantidad de puestos de trabajo',
    type: 'number',
    placeholder: '',
    required: false,
  },
  {
    name: 'message',
    label: 'Mensaje',
    type: 'text',
    placeholder: 'Mensaje',
    required: false,
  },
];
