export const INTIAL_COWORKING_INFO = {
  name: "",
  lastname: "",
  phone: "+54",
  email: "",
  identification: "",
  position: "",
  companyName: "",
  companyEmail: "",
  companyPhone: "+54",
  address: "",
  website: "",
  open: "",
  close: "",
  capacity: 0,
  message: "",
}

export const INITIAL_COWORKING_INFO_ERROR = {
  name: "",
  lastname: "",
  phone: "",
  email: "",
  identification: "",
  position: "",
  companyName: "",
  companyEmail: "",
  companyPhone: "",
  address: "",
  website: "",
  open: "",
  close: "",
  capacity: "",
  message: "",
}